# Generated by Django 6.0.1 on 2026-03-31 09:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vehiclelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5),
        ),
    ]
